const { colors } = require("./colors");
const { fonts } = require("./fonts");
const { spacing } = require("./spacing");
const { borders } = require("./borders");
const { getREM, getPX, getEM } = require("./utils");

const theme = {
    colors: {
        primary: colors.gold,
        secondary: colors.deepBlue,
        neutrals: colors.neutrals,
        success: colors.pickleGreen,
        warning: colors.mustardYellow,
        error: colors.chilliRed,
        disabled: colors.cloudGray,
        inDepoNeutrals: colors.inDepoNeutrals,
        inDepoBlue: colors.inDepoBlue,
        inDepoRed: colors.inDepoRed,
    },
    default: {
        /** Ant Design */
        // Color
        primaryColor: colors.gold[5], // color base
        infoColor: colors.gold[5],
        processingColor: colors.gold[5],
        successColor: colors.pickleGreen[5],
        warningColor: colors.mustardYellow[5],
        errorColor: colors.chilliRed[5],
        highlightColor: colors.chilliRed[5],
        disabledColor: colors.cloudGray[7],
        disabledBg: colors.cloudGray[5],
        whiteColor: colors.neutrals[6],
        blackColor: colors.neutrals[0],
        // Font
        textColor: colors.neutrals[0],
        textColorInverse: colors.neutrals[6],
        fontFamily: fonts.fontFamily,
        codeFontFamily: fonts.codeFontFamily,
        fontSizeBase: fonts.fontSizeBase,
        lineHeightBase: fonts.lineHeightBase,
        typographyTitleFontWeight: fonts.typographyTitleFontWeight,
        typographyTitleMarginTop: fonts.typographyTitleMarginTop,
        typographyTitleMarginBottom: fonts.typographyTitleMarginBottom,
        // Border
        borderRadiusBase: borders.borderRadiusBase,
        // Button
        btnFontWeight: 700,
        btnHeightBase: spacing.heightBase,
        // Input
        inputHeightBase: spacing.heightBase,
        /** Custom */
        secondary: colors.deepBlue[5], // color base
        baseUnit: spacing.baseUnit,
        headerFontFamily: fonts.headerFontFamily,
        fontSizes: fonts.fontSizes,
        spaces: spacing.spaces,
        heightBase: spacing.heightBase,
        fontWeights: fonts.fontWeights,
    },
    mode: "default",
};

/** Override Ant Design variables */
const modifiedVariables = {
    "@text-color": theme.default.textColor,
    "@primary-color": theme.default.primaryColor,
    "@info-color": theme.default.infoColor,
    "@success-color": theme.default.successColor,
    "@processing-color": theme.default.processingColor,
    "@error-color": theme.default.errorColor,
    "@highlight-color": theme.default.highlightColor,
    "@warning-color": theme.default.warningColor,
    "@disabled-color": theme.default.disabledColor,
    "@alert-info-border-color": theme.default.infoColor,
    "@alert-success-border-color": theme.default.successColor,
    "@alert-warning-border-color": theme.default.warningColor,
    "@alert-error-border-color": theme.default.errorColor,
    "@alert-warning-bg-color": theme.colors.warning[2],
    "@alert-icon-top": getREM(theme.default.fontSizes[4] / 2 + theme.default.baseUnit - 1),
    "@font-family": theme.default.fontFamily,
    "@code-family": theme.default.codeFontFamily,
    "@font-size-base": getREM(theme.default.fontSizeBase),
    "@font-size-sm": getREM(theme.default.fontSizes[8]),
    "@font-size-lg": getREM(theme.default.fontSizes[6]),
    "@heading-1-size": getREM(theme.default.fontSizes[0]),
    "@heading-2-size": getREM(theme.default.fontSizes[1]),
    "@heading-3-size": getREM(theme.default.fontSizes[2]),
    "@heading-4-size": getREM(theme.default.fontSizes[3]),
    "@heading-5-size": getREM(theme.default.fontSizes[4]),
    "@line-height-base": theme.default.lineHeightBase,
    "@typography-title-font-weight": theme.default.typographyTitleFontWeight,
    "@typography-title-margin-top": getEM(theme.default.typographyTitleMarginTop),
    "@typography-title-margin-bottom": getEM(theme.default.typographyTitleMarginBottom),
    "@border-radius-base": getPX(theme.default.borderRadiusBase, spacing.baseUnit),
    "@btn-font-weight": theme.default.btnFontWeight,
    "@btn-height-base": getREM(theme.default.btnHeightBase),
    "@btn-padding-horizontal-base": getREM(theme.default.spaces[9]),
    "@btn-disable-color": theme.default.disabledColor,
    "@btn-disable-bg": theme.default.disabledBg,
    "@btn-disable-border": theme.default.disabledBg,
    "@input-height-base": getPX(theme.default.inputHeightBase, theme.default.baseUnit),
    "@input-padding-horizontal": getREM(theme.default.spaces[6]),
    "@input-padding-vertical-base": getREM(theme.default.spaces[5]),
    "@input-disabled-bg": theme.default.disabledBg,
    "@input-disabled-color": theme.default.disabledColor,
    "@form-item-label-font-size": getREM(theme.default.fontSizes[8]),
    "@form-vertical-label-padding": `0 0 ${getREM(theme.default.spaces[3])}`,
    "@layout-header-background": theme.colors.neutrals[6],
    "@layout-sider-background": theme.colors.secondary[5],
    "@menu-item-height": getREM(theme.default.spaces[8] * 2),
    "@menu-icon-size": getREM(theme.default.spaces[9]),
    "@menu-dark-bg": theme.colors.secondary[5],
    "@menu-dark-item-active-bg": theme.colors.secondary[4],
    "@layout-body-background": theme.colors.neutrals[5],
    "@layout-header-height": getREM(theme.default.spaces[6] * 4),
    "@layout-header-padding": getREM(theme.default.spaces[6]),
    "@result-icon-font-size": getREM(theme.default.spaces[7] * 4),
    "@result-title-font-size": getREM(theme.default.spaces[9]),
    "@result-extra-margin": `${getREM(theme.default.spaces[12])} 0 0 0`,
    "@card-padding-base": getREM(theme.default.spaces[8] * 4),
    "@table-bg": "transparent",
    "@table-header-bg": "transparent",
    "@table-header-color": theme.colors.disabled[7],
    "@calendar-item-active-bg": theme.default.primaryColor,
    "@picker-basic-cell-hover-color": theme.colors.neutrals[3],
    "@select-item-active-bg": theme.colors.neutrals[3],
    "@select-item-selected-bg": theme.default.primaryColor,
    "@select-item-selected-color": theme.default.whiteColor,
    "@select-item-selected-font-weight": "500",
    "@list-item-padding": `${getREM(theme.default.spaces[6])}`,
    "@list-item-padding-sm": `${getREM(theme.default.spaces[4])} ${getREM(theme.default.spaces[6])}`,
    "@list-item-padding-lg": `${getREM(theme.default.spaces[6])} ${getREM(theme.default.spaces[9])}`,
};

module.exports = { theme, modifiedVariables };
