name: Manual Deployment

on: [workflow_dispatch]

jobs:
    build-test:
        runs-on: ubuntu-latest
        if: contains('
            refs/heads/uat
            refs/heads/prod
            ', github.ref)
        steps:
            - uses: actions/checkout@v2
            - name: Cache node modules
              id: yarn-cache
              uses: actions/cache@v2
              env:
                  cache-name: cache-node-modules
              with:
                  path: "**/node_modules"
                  key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/yarn.lock') }}
                  restore-keys: |
                      ${{ runner.os }}-build-${{ env.cache-name }}-
                      ${{ runner.os }}-build-
                      ${{ runner.os }}-

            - uses: webfactory/ssh-agent@v0.4.1
              with:
                ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

            - name: Install Dependencies
              if: steps.yarn-cache.outputs.cache-hit != 'true'
              run: yarn install

            - name: Extract Branch Name for ENV file replacement
              id: extract-branch-for-replacement
              shell: bash
              run: echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})"              

            - name: Getting appropriate ENV file
              if: endsWith(github.ref, 'uat') || endsWith(github.ref, 'prod')
              uses: canastro/copy-file-action@master
              with:
                  source: ./env/.env.${{ steps.extract-branch-for-replacement.outputs.branch }}
                  target: .env

            - name: Prebuild
              run: yarn prebuild

            - name: Build
              run: ESLINT_NO_DEV_ERRORS=true DISABLE_ESLINT_PLUGIN=true yarn build
            - name: Test
              run: CI=true yarn test
            - name: Upload publish to GitHub Store
              uses: actions/upload-artifact@master
              with:
                  name: publish-build
                  path: ./build
                  retention-days: 1

    pack-deploy:
        runs-on: ubuntu-latest
        if: contains('
            refs/heads/uat
            refs/heads/prod
            ', github.ref)        
        needs: [build-test]
        steps:
            - uses: actions/checkout@v2
            - name: Extract Branch Name
              id: extract-branch
              shell: bash
              run: echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})"
            
            - name: Getting appropriate ENV file
              uses: canastro/copy-file-action@master
              with:
                  source: ./env/.env.${{ steps.extract-branch.outputs.branch }}
                  target: .env

            - name: Configure AWS Credentials
              uses: aws-actions/configure-aws-credentials@v1
              with:
                  aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
                  aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
                  aws-region: us-east-1
            - name: Download publish from GitHub Store
              uses: actions/download-artifact@master
              with:
                  name: publish-build
                  path: ./build

            - name: Extract Bucket & CloudFront Distribution Id for UAT
              if: ${{ steps.extract-branch.outputs.branch == 'uat' }}
              shell: bash
              env:
                  DIST: ${{ secrets.DISTRIBUTION_UAT }}
              run: |
                  echo "DISTRIBUTION=$DIST" >> $GITHUB_ENV
                  echo "BUCKET=prp-fe-uat" >> $GITHUB_ENV
                  echo "REGION=us-east-1" >> $GITHUB_ENV
            - name: Extract Bucket & CloudFront Distribution Id for PROD
              if: ${{ steps.extract-branch.outputs.branch == 'prod' }}
              shell: bash
              env:
                  DIST: ${{ secrets.DISTRIBUTION_PROD }}
              run: |
                  echo "DISTRIBUTION=$DIST" >> $GITHUB_ENV
                  echo "BUCKET=prp-fe-prod" >> $GITHUB_ENV
                  echo "REGION=us-east-2" >> $GITHUB_ENV
            - name: Upload publish to S3
              run: |
                  aws s3 sync ./build s3://$BUCKET --metadata-directive REPLACE --cache-control 'max-age=86400,must-revalidate,public' --delete --region $REGION

                  cd build/webviewer/lib/core/pdf/lean

                  arr=(`ls *.br.*`)
                  for ((i=0; i < ${#arr[@]}; i++)); do
                    aws s3 cp ${arr[$i]} s3://$BUCKET/webviewer/lib/core/pdf/lean/ --content-encoding br --metadata-directive REPLACE --cache-control 'max-age=86400,must-revalidate,public' --region $REGION
                    echo "${arr[$i]}"
                  done

                  arr=(`ls *.gz.*`)
                  for ((i=0; i < ${#arr[@]}; i++)); do
                    aws s3 cp ${arr[$i]} s3://$BUCKET/webviewer/lib/core/pdf/lean/ --content-encoding gz --metadata-directive REPLACE --cache-control 'max-age=86400,must-revalidate,public' --region $REGION
                    echo "${arr[$i]}"
                  done

                  aws cloudfront create-invalidation --distribution-id $DISTRIBUTION --paths "/*" --region $REGION
