name: SonarQube Analysis for Front End

on:
  push:
    branches:
      - develop
      
jobs:
  analyze:
    runs-on: ubuntu-latest
    steps:
    - name: Checking out
      uses: actions/checkout@v2
      with:
        fetch-depth: 0    
    - name: Sonarqube Scan
      uses: kitabisa/sonarqube-action@master
      with:
        host: "https://sonarqube.prdevelopment.net"
        projectKey: "prp-fe"
        projectName: "prp-fe"
        login: ${{ secrets.SONAR_TOKEN }}
