name: SonarQube Analysis for Front End

on:
  push:
    branches:
      - develop

jobs:
  analyze:
    runs-on: ubuntu-latest
    steps:
      - name: Checking out
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - uses: webfactory/ssh-agent@v0.4.1
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
      - name: Install Dependencies
        run: yarn install

      - name: Test
        run: CI=true yarn test --coverage --watchAll=false

      - name: Sonarqube Scan
        uses: kitabisa/sonarqube-action@master
        with:
          host: "https://sonarqube.prdevelopment.net"
          projectKey: "prp-fe"
          projectName: "prp-fe"
          login: ${{ secrets.SONAR_TOKEN }}
