name: SonarQube Analysis for Front End

on:
  push:
    branches:
      - develop

jobs:
  analyze:
    runs-on: ubuntu-latest
    steps:
      - name: Checking out
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - uses: webfactory/ssh-agent@v0.4.1
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
            
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1      
      
      - name: Install Dependencies
        run: sh yarn-install.sh

      - name: Test
        run: CI=true yarn test --coverage --watchAll=false

      - name: Sonarqube Scan
        uses: kitabisa/sonarqube-action@master
        with:
          host: "https://sonarqube.prdevelopment.net"
          projectKey: "prp-fe"
          projectName: "prp-fe"
          login: ${{ secrets.SONAR_TOKEN }}
